#!/usr/bin/env python3
"""Dump the game's own item tables into web/items.js.

The browser patcher needs item names and vanilla prices before a disc is even
chosen, so they are committed as data. This is how that data is produced, so
it can be regenerated rather than trusted:

    python3 tools/gen_items.py "Azure Dreams (USA).bin" > web/items.js

Everything comes from the category descriptor table at RAM 0x80073414 in
slus_006.14 (see docs/FINDINGS.md, "Items are uniform"). Nothing is typed in
by hand except the category labels and which categories a shop may stock.
"""
from __future__ import annotations

import json
import struct
import sys
import unicodedata

SECTOR, HDR, DATA = 0x930, 0x18, 0x800
SLUS_DELTA = 0x80020800            # slus RAM -> stream offset
CAT_TABLE = 0x80073414
CAT_STRIDE = 20
ITEM_RECORD = 20

# The egg array is in main.bin, not slus; its RAM address is what the
# category table holds, and this is where the same bytes sit on disc.
EGG_ARRAY_RAM = 0x8002CA68
EGG_ARRAY_STREAM = 0x003ADA68

# id, label, and whether Barry / the monster shop may stock it. Categories not
# listed (gifts, quest items, coins, familiars, traps...) are left alone: they
# are not shop goods and some are references into other structures.
CATEGORIES = [
    (0x01, 'herb',    'Herbs',    True,  False),
    (0x02, 'fruit',   'Fruit',    True,  False),
    (0x03, 'seed',    'Seeds',    True,  False),
    (0x04, 'ball',    'Balls',    True,  False),
    (0x05, 'scroll',  'Scrolls',  True,  False),
    (0x06, 'crystal', 'Crystals', True,  False),
    (0x07, 'bell',    'Bells',    True,  False),
    (0x08, 'glasses', 'Glasses',  True,  False),
    (0x09, 'loupe',   'Loupes',   True,  False),
    (0x0a, 'sand',    'Sands',    True,  False),
    (0x0f, 'sword',   'Swords',   True,  False),
    (0x10, 'wand',    'Wands',    True,  False),
    (0x11, 'shield',  'Shields',  True,  False),
    (0x12, 'egg',     'Eggs',     True,  True),
]

# Rows the table lists but the game never hands out as goods. Ball ids 0x0a,
# 0x0f, 0x0x10 have no name; egg 0x2e onward are NPCs and scenery given egg
# rows for the monster book. Sword 0x0b is the cutscene Seraphim.
SKIP = {(0x0f, 0x0b)}
MAX_EGG = 0x2d

# Disambiguate the two "Medicinal" herbs.
ALIASES = {(0x01, 0x01): 'Medicinal (hospital)', (0x01, 0x0f): 'Medicinal (tower)'}


def main(path: str) -> None:
    with open(path, 'rb') as f:
        img = f.read()

    def read(stream: int, n: int) -> bytes:
        out = bytearray()
        while n:
            lba, w = divmod(stream, DATA)
            k = min(DATA - w, n)
            off = lba * SECTOR + HDR + w
            out += img[off:off + k]
            stream += k
            n -= k
        return bytes(out)

    def u16(b, o=0):
        return struct.unpack_from('<H', b, o)[0]

    def u32(b, o=0):
        return struct.unpack_from('<I', b, o)[0]

    def ram_to_stream(ram: int) -> int:
        if ram >= 0x8002D000:
            return ram - SLUS_DELTA
        if ram >= 0x80020000:
            # main.bin: the egg array and, just below it, the egg names.
            return ram - EGG_ARRAY_RAM + EGG_ARRAY_STREAM
        raise SystemExit(f'pointer 0x{ram:08x} is in neither slus nor main.bin')

    def name_at(ram: int) -> str:
        if not ram:
            return ''
        raw = read(ram_to_stream(ram), 48)
        raw = raw[:raw.find(b'\0')] if b'\0' in raw else raw
        s = unicodedata.normalize('NFKC', raw.decode('shift_jis', errors='replace'))
        return s.replace('−', '-').replace('’', "'").strip()

    cats = []
    items = []
    for cat, key, label, barry, monster in CATEGORIES:
        rec = read(CAT_TABLE - SLUS_DELTA + cat * CAT_STRIDE, CAT_STRIDE)
        count, arr, price_fn = rec[2], u32(rec, 12), u32(rec, 8)
        cats.append({'cat': cat, 'key': key, 'label': label, 'arr': arr,
                     'scaled': price_fn != 0, 'barry': barry, 'monster': monster})
        limit = min(count, MAX_EGG) if cat == 0x12 else count
        for iid in range(1, limit + 1):
            if (cat, iid) in SKIP:
                continue
            r = read(ram_to_stream(arr) + iid * ITEM_RECORD, ITEM_RECORD)
            name = ALIASES.get((cat, iid)) or name_at(u32(r, 4))
            if not name:
                continue
            items.append({'cat': cat, 'id': iid, 'name': name,
                          'buy': u16(r, 16), 'sell': u16(r, 18)})

    out = sys.stdout
    out.write('// Generated by tools/gen_items.py from an unmodified Azure Dreams (USA)\n')
    out.write('// image. Names and prices are the game\'s own; do not edit by hand.\n\n')
    out.write('export const CATEGORIES = [\n')
    for c in cats:
        out.write(f"  {{ cat: 0x{c['cat']:02x}, key: '{c['key']}', label: '{c['label']}', "
                  f"arr: 0x{c['arr']:08x}, scaled: {str(c['scaled']).lower()}, "
                  f"barry: {str(c['barry']).lower()}, monster: {str(c['monster']).lower()} }},\n")
    out.write('];\n\nexport const ITEMS = [\n')
    for it in items:
        out.write(f"  {{ cat: 0x{it['cat']:02x}, id: 0x{it['id']:02x}, "
                  f"name: {json.dumps(it['name'])}, buy: {it['buy']}, sell: {it['sell']} }},\n")
    out.write('];\n')


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
